language: python
group: travis_latest
dist: xenial
sudo: true

env:
    global:
        - github_master="https://github.com/${TRAVIS_REPO_SLUG}/archive/master.zip"

addons:
    apt:
        packages:
            - xvfb
            - winbind
    #################################################################################
matrix:
    include:
    #################################################################################
    - os: linux
      language: python
      python: '2.7'
    #################################################################################
    - os: linux
      language: python
      python: '3.4'
    #################################################################################
    - os: linux
      language: python
      python: '3.5'
    #################################################################################
    - os: linux
      language: python
      python: '3.6'
    #################################################################################
    - os: linux
      language: python
      python: '3.7.1'
    #################################################################################
    - os: linux
      language: python
      python: '3.7-dev'
    #################################################################################
    - os: linux
      language: python
      python: 'pypy2.7-6.0'
    #################################################################################
    - os: linux
      language: python
      python: 'pypy3.5-6.0'
    #################################################################################
    - os: windows
      language: sh
      name: "Windows Python 2.7"
      before_install:
          - choco install python2
          - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
    #################################################################################
    - os: windows
      language: sh
      name: "Windows Python 3.7"
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
    #################################################################################
    # WINE Stable XP
    #################################################################################
    - os: linux
      language: sh
      name: "WINE stable 32 Bit Python 2.7.16, Windows XP"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - WINEPATH="c:/PortableGit32/cmd;c:/Python27-32;c:/Python27-32/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="stable"
          - wine_python_version="python2"
    #################################################################################
    - os: linux
      language: sh
      name: "WINE stable 64 Bit Python 2.7.16, Windows XP"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - WINEPATH="c:/PortableGit64/cmd;c:/Python27-64;c:/Python27-64/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="stable"
          - wine_python_version="python2"
    #################################################################################
    - os: linux
      language: sh
      name: "WINE stable 32 Bit Python 3.7.3, Windows XP"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - WINEPATH="c:/PortableGit32/cmd;c:/Python37-32;c:/Python37-32/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="stable"
          - wine_python_version="python3"
    #################################################################################
    - os: linux
      language: sh
      name: "WINE stable 64 Bit Python 3.7.3, Windows XP"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - WINEPATH="c:/PortableGit64/cmd;c:/Python37-64;c:/Python37-64/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="stable"
          - wine_python_version="python3"
    #################################################################################
    # WINE Stable WIN10
    #################################################################################
    - os: linux
      language: sh
      name: "WINE stable 32 Bit Python 2.7.16, Windows 10"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - WINEPATH="c:/PortableGit32/cmd;c:/Python27-32;c:/Python27-32/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="stable"
          - wine_python_version="python2"
    #################################################################################
    - os: linux
      language: sh
      name: "WINE stable 64 Bit Python 2.7.16, Windows 10"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - WINEPATH="c:/PortableGit64/cmd;c:/Python27-64;c:/Python27-64/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="stable"
          - wine_python_version="python2"
    #################################################################################
    - os: linux
      language: sh
      name: "WINE stable 32 Bit Python 3.7.3, Windows 10"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - WINEPATH="c:/PortableGit32/cmd;c:/Python37-32;c:/Python37-32/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="stable"
          - wine_python_version="python3"
    #################################################################################
    - os: linux
      language: sh
      name: "WINE stable 64 Bit Python 3.7.3, Windows 10"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - WINEPATH="c:/PortableGit64/cmd;c:/Python37-64;c:/Python37-64/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="stable"
          - wine_python_version="python3"
    #################################################################################
    # WINE Develop XP
    #################################################################################
    - os: linux
      language: sh
      name: "WINE devel 32 Bit Python 2.7.16, Windows XP"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - WINEPATH="c:/PortableGit32/cmd;c:/Python27-32;c:/Python27-32/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="devel"
          - wine_python_version="python2"
    #################################################################################
    - os: linux
      language: sh
      name: "WINE devel 64 Bit Python 2.7.16, Windows XP"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - WINEPATH="c:/PortableGit64/cmd;c:/Python27-64;c:/Python27-64/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="devel"
          - wine_python_version="python2"
    #################################################################################
    - os: linux
      language: sh
      name: "WINE devel 32 Bit Python 3.7.3, Windows XP"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - WINEPATH="c:/PortableGit32/cmd;c:/Python37-32;c:/Python37-32/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="devel"
          - wine_python_version="python3"
    #################################################################################
    - os: linux
      language: sh
      name: "WINE devel 64 Bit Python 3.7.3, Windows XP"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - WINEPATH="c:/PortableGit64/cmd;c:/Python37-64;c:/Python37-64/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="devel"
          - wine_python_version="python3"
    #################################################################################
    # WINE Develop WIN10
    #################################################################################
    - os: linux
      language: sh
      name: "WINE devel 32 Bit Python 2.7.16, Windows 10"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - WINEPATH="c:/PortableGit32/cmd;c:/Python27-32;c:/Python27-32/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="devel"
          - wine_python_version="python2"
    #################################################################################
    - os: linux
      language: sh
      name: "WINE devel 64 Bit Python 2.7.16, Windows 10"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - WINEPATH="c:/PortableGit64/cmd;c:/Python27-64;c:/Python27-64/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="devel"
          - wine_python_version="python2"
    #################################################################################
    - os: linux
      language: sh
      name: "WINE devel 32 Bit Python 3.7.3, Windows 10"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - WINEPATH="c:/PortableGit32/cmd;c:/Python37-32;c:/Python37-32/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="devel"
          - wine_python_version="python3"
    #################################################################################
    - os: linux
      language: sh
      name: "WINE devel 64 Bit Python 3.7.3, Windows 10"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - WINEPATH="c:/PortableGit64/cmd;c:/Python37-64;c:/Python37-64/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="devel"
          - wine_python_version="python3"
    #################################################################################
    # WINE Staging XP
    #################################################################################
    - os: linux
      language: sh
      name: "WINE staging 32 Bit Python 2.7.16, Windows XP"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - WINEPATH="c:/PortableGit32/cmd;c:/Python27-32;c:/Python27-32/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="staging"
          - wine_python_version="python2"
    #################################################################################
    - os: linux
      language: sh
      name: "WINE staging 64 Bit Python 2.7.16, Windows XP"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - WINEPATH="c:/PortableGit64/cmd;c:/Python27-64;c:/Python27-64/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="staging"
          - wine_python_version="python2"
    #################################################################################
    - os: linux
      language: sh
      name: "WINE staging 32 Bit Python 3.7.3, Windows XP"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - WINEPATH="c:/PortableGit32/cmd;c:/Python37-32;c:/Python37-32/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="staging"
          - wine_python_version="python3"
    #################################################################################
    - os: linux
      language: sh
      name: "WINE staging 64 Bit Python 3.7.3, Windows XP"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - WINEPATH="c:/PortableGit64/cmd;c:/Python37-64;c:/Python37-64/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="winxp"
          - wine_version="staging"
          - wine_python_version="python3"
    #################################################################################
    # WINE Develop WIN10
    #################################################################################
    - os: linux
      language: sh
      name: "WINE staging 32 Bit Python 2.7.16, Windows 10"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - WINEPATH="c:/PortableGit32/cmd;c:/Python27-32;c:/Python27-32/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="staging"
          - wine_python_version="python2"
    #################################################################################
    - os: linux
      language: sh
      name: "WINE staging 64 Bit Python 2.7.16, Windows 10"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - WINEPATH="c:/PortableGit64/cmd;c:/Python27-64;c:/Python27-64/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="staging"
          - wine_python_version="python2"
    #################################################################################
    - os: linux
      language: sh
      name: "WINE staging 32 Bit Python 3.7.3, Windows 10"
      env:
          - WINEARCH="win32"
          - WINEPREFIX="${HOME}/wine/wine32"
          - WINEPATH="c:/PortableGit32/cmd;c:/Python37-32;c:/Python37-32/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="staging"
          - wine_python_version="python3"
    #################################################################################
    - os: linux
      language: sh
      name: "WINE staging 64 Bit Python 3.7.3, Windows 10"
      env:
          - WINEPREFIX="${HOME}/wine/wine64"
          - WINEPATH="c:/PortableGit64/cmd;c:/Python37-64;c:/Python37-64/Scripts"
          - CMDPREFIX="wine"
          - wine_windows_version="win10"
          - wine_version="staging"
          - wine_python_version="python3"

    #################################################################################
    #################################################################################
    #################################################################################
    #################################################################################
    #################################################################################
    #################################################################################
    - os: osx
      language: sh
      name: "osX Python 2.7"
    #################################################################################
    - os: osx
      language: sh
      name: "osX Python 3.6"
    #################################################################################


install:
    - if [[ ${CMDPREFIX} == "wine" ]]; then chmod 755 ./*.sh ; fi
    - if [[ ${CMDPREFIX} == "wine" ]]; then ./install_wine.sh ; fi
    - if [[ ${CMDPREFIX} == "wine" ]]; then ./install_wine_machine.sh ; fi
    - if [[ ${wine_python_version} == "python2" ]]; then ./install_wine_python2_preinstalled.sh ; fi
    - if [[ ${wine_python_version} == "python3" ]]; then ./install_wine_python3_preinstalled.sh ; fi
    - if [[ ${CMDPREFIX} == "wine" ]]; then ./install_wine_git_portable.sh ; fi

    - ${CMDPREFIX} python -m pip install --upgrade pip
    - if [[ $TRAVIS_PYTHON_VERSION == pypy3.5-6.0 ]]; then ${CMDPREFIX} pip install "pytest-cov==2.6.0"; fi
    - ${CMDPREFIX} pip install codecov pytest pytest-pep8 pytest-cov dill
    - ${CMDPREFIX} pip install -e .

script:
    - ${CMDPREFIX} pip install ${github_master} --install-option test # test setup.py test option
    - ${CMDPREFIX} python -m pytest --pep8 --cov
after_success:
    - ${CMDPREFIX} coverage report
    - ${CMDPREFIX} codecov


## PYPI
deploy:
  provider: pypi
  user: bitranox
  password:
      secure: "umgp9FS+RHgjt6SBzbf0uufTkYl3KNmt2S9cY2HlRXwiiyUt8WTHK64mDaA2Vijd/V7BixvlnNAmWbdb23pysUua5PKG+FZbK8dONTxPYHWTp8sesMGDmMdVNuKNql+6pKGPRXEBSaszyaXHykmOholpnlUVTpfYxvni/UcaEzfnLIV44lULmpw9noR1uAaerpU9EcInlEymBTP0vjciojfQGzFNjD+g4E8qNUHpDxpFER3E6F3IDVDltOzjhYqpvlgEHVcXpY1atVGWvW5cGUsYTr5wGe3PvCcl4oXRFEei+nTU0pD4Ri32QCzrD3yHVcZ8SUCo1VDm3I8FwJXDsS9rZOsS/62SNaEa5yTbV7FeKhc2o1zvoBiSsQYPiEDsYamYyh+kCGPKOGPGA3whWOWbVrA4qqG9YGTNEBEGOwNkUBqkDuNTGl4aFEPFqdFyYIss1Bxm+oz/YF1AsYg5OBn2obibwbf/e298ywan/LihtX2X0bO9J4ossRgc713B4YveTuyq2aC5Fu1oNtauUyl+f/odmHIaYwBVVbLai2AZwB9c5x5RgL17lAAFSrQ35eU05CTFGnxQRN85G/bjc6L0yJKvH/XlRsEKNykl7ZxW0G0IseINiB1j5y2QTPxKismDZ3pp04Z1uYsKd8jxRlWr53wCL2snV5VLgrTt4x8="
  distributions: "sdist bdist_wheel"
  on:
      tags: true
      python: 3.6
