language: python
group: travis_latest
dist: xenial

sudo: false

python:
# - '2.6'    # 2019-02-24 dropped Python 2.6 Support, since wrapt dropped it
- '2.7'
- '3.4'
- '3.5'
- '3.6'
# - '3.7'     # 2018-09-10 Python 3.7 not installed on travis
- '3.7.1'     # 2019-03-25 latest Version
- '3.7-dev'   # 2018-03-25 development Version
# - '3.8-dev' # 2018-09-10 does not exist now
- 'pypy2.7-6.0'
- 'pypy3.5'

matrix:
  include:

#  - os: linux
#    language: python
#    install:
#    - pip install --upgrade pip
#    - if [[ $TRAVIS_PYTHON_VERSION == 3.2 ]]; then pip install -U "virtualenv<14.0.0"; fi
#    - pip install tox tox-travis dill multiprocess wrapt codecov

  - os: osx
    language: sh
    install:
    - pip3 install --upgrade pip
    - pip3 install tox tox-travis dill multiprocess wrapt codecov pytest-pep8 pytest-cov

  - os: windows
    language: sh
    before_install:
    - choco install python3
    - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
    - python -m pip install --upgrade pip
    - pip install tox tox-travis dill multiprocess wrapt codecov pytest-pep8 pytest-cov

install:
- if [[ $TRAVIS_PYTHON_VERSION == 3.2 ]]; then pip install -U "virtualenv<14.0.0"; fi
- pip install --upgrade pip
- pip install tox tox-travis dill multiprocess wrapt codecov pytest-pep8 pytest-cov

script:
  # - tox
  - py.test --pep8 --cov tests

after_success:
- pip install -e .
- coverage combine --append
- coverage report
- codecov


#deploy:
#  provider: pypi
#  user: png
#  password:
#    secure: ZXoq3kgfu+IICjhhmQZr0s0xE6bvWzH04GjdE/VL4BxdDdGI4fHEwudGEjzLXJbt2d09vNOO67Nqam+MwPWtq+WZEP69g/Fhyy4kbkuUl/CMeqashQzU/N+3lwv97Y2qvzTUwDnSoz4zyBFu67SSrovKruFsYaiH00bwvWcvLa0=
#  on:
#    python: 2.7
